### ISSUE TITLE
Update to the new `empack`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#128]
### Problem

A few projects in the emscripten forge organization have now been updated to use the new `empack >=3.0.0`:

- https://github.com/emscripten-forge/pyjs-code-runner
- https://github.com/emscripten-forge/sample-python-repl

### Proposed Solution

Update the xeus python kernel to `empack>=3.0.0`.

This will likely require the next version of `jupyterlite-xeus-python` to be `0.9.0`.

**Comment by martinRenou** [comment]
This may help me finish https://github.com/conda-forge/staged-recipes/pull/22492 as well, because it may help supporting Windows

**Comment by DerThorsten** [comment]
for that, we need a new release /tag in  of xeus python (with this in https://github.com/jupyter-xeus/xeus-python/pull/588)
Then we can put that version on `emscripten-forge` 
Once we have that we can use the whole `empack >= 3.0.0` stack here

**Comment by jtpio** [comment]
> for that, we need a new release /tag in of xeus python (with this in [jupyter-xeus/xeus-python#588](https://github.com/jupyter-xeus/xeus-python/pull/588))

@martinRenou or @DerThorsten would you be able to make a new release of Xeus Python? Thanks!

**Comment by DerThorsten** [comment]
> > for that, we need a new release /tag in of xeus python (with this in [jupyter-xeus/xeus-python#588](https://github.com/jupyter-xeus/xeus-python/pull/588))
> 
> @martinRenou or @DerThorsten would you be able to make a new release of Xeus Python? Thanks!

[xeus-python 0.15.9](https://github.com/jupyter-xeus/xeus-python/releases/tag/0.15.9) is out!

**Comment by jtpio** [comment]
Nice thanks!

Just opened https://github.com/emscripten-forge/recipes/pull/449

**Comment by JeongJun-Lee** [comment]
is the reason why I met this error on the jupyter lite build command: FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/share/empack/empack_config.yaml'?

**Comment by martinRenou** [comment]
@JeongJun-Lee I think this is unrelated, would you be able to open your own issue with more in-depth information about your setup, like the empack version and how you installed it?

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/xeus-python-kernel/pull/134, thanks!
