### ISSUE TITLE
Package conflicts when trying a build

### ISSUE THREAD

**Issue by JeongJun-Lee** [jupyterlite/xeus-python-kernel#131]
## Description

Package conflicts when trying a build by "jupyter lite build" command

## Expected behavior

Should be no error

## Context

- JupyterLite version: jupyter_core     : 5.3.0
- Operating System and version: mac 10.15.7
- Browser and version: 

<details><summary>Build Output</summary>
<pre>
jupyterlite-pyodide-kernel-piplite:patch
jupyterlite-xeus-python:xeus:copy:ext:@jupyterlite/xeus-python-kernel
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /tmp/xeus-python-kernel/envs/xeus-python-kernel

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /tmp/xeus-python-kernel/envs/xeus-python-kernel
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
xeus-python -> ipython -> python[version='>=3.6|>=3.8|>=3.9']
pip -> python[version='>=3|>=3.6|>=3.7']
xeus-python -> python
jupyterlab -> async-lru[version='>=1.0.0'] -> python[version='>=2.7|>=3.4|>=3.9']
pip -> setuptools -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4|>=3.8|2.7.*|>=3.6']
jupyterlab -> python[version='>=3.5|>=3.6|>=3.7|>=3.8']

Package packaging conflicts for:
jupyterlab -> packaging
jupyterlab -> jupyterlab_server[version='>=2.19.0,<3'] -> packaging[version='>=21.3']

Package traitlets conflicts for:
jupyterlab -> ipykernel -> traitlets[version='>=4.2.1|>=5.1|>=5.3.0|>=5|>=5.1.0|>=5.4.0|>=5.6.0']
jupyterlab -> traitlets

Package stack_data conflicts for:
xeus-python -> ipython -> stack_data
jupyterlab -> ipython -> stack_data

Package emscripten-abi conflicts for:
xeus-lite -> emscripten-abi=3.1.27
python=3.10 -> emscripten-abi=3.1.27
pip -> python[version='>=3.7'] -> emscripten-abi=3.1.27
xeus-python -> emscripten-abi=3.1.27
jupyterlab -> python[version='>=3.8'] -> emscripten-abi=3.1.27

Package pyparsing conflicts for:
pip -> setuptools -> pyparsing
jupyterlab -> packaging -> pyparsing[version='<3,>=2.0.2|>=2.0.2,!=3.0.5|>=2.0.2,<3|>=2.0.2']

Package wheel conflicts for:
pip -> wheel
jupyterlab -> jupyter-packaging[version='>=0.7,<1'] -> wheel
python=3.10 -> pip -> wheel

Package ipython conflicts for:
jupyterlab -> ipykernel -> ipython[version='>=7.23.1']
jupyterlab -> ipythonThe following specifications were found to be incompatible with your system:

  - jupyterlab -> ipykernel -> __linux
  - jupyterlab -> ipykernel -> __osx
  - jupyterlab -> ipykernel -> __win

Your installed version is: not available

[LiteBuildApp] ERROR | [lite] [post_build] [jupyterlite-xeus-python] [ERR] Command '['/Users/xxx/miniconda/condabin/conda', 'install', '--yes', '--prefix', PosixPath('/tmp/xeus-python-kernel/envs/xeus-python-kernel'), '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'https://repo.mamba.pm/conda-forge', '-c', 'conda-forge', 'python=3.10', 'xeus-lite', 'xeus-python', 'python', 'pip', 'jupyterlab']' returned non-zero exit status 1.
</pre>
</details>

**Comment by martinRenou** [comment]
Thanks for opening an issue. Could you please provide the environment.yml file that you used?

**Comment by JeongJun-Lee** [comment]
name: xeus-python-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab

**Comment by martinRenou** [comment]
If this is the environment file for the xeus-python environment, it looks incorrect.

It should look more like:
```yml
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - numpy
```

- You were missing the emscripten-forge channel
- No need for a "jupyterlab" dependency or "python"/"pip", it's implicitly there already
