### ISSUE TITLE
Mix using Python and Javascript in Xeus just like in Pyodide

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/xeus-python-kernel#154]
It is said "Pyodide comes with a robust Javascript ⟺ Python foreign function interface so that you can freely mix these two languages in your code with minimal friction. " at https://pyodide.org/en/stable/ .

I am just wondering whether xeus-python has similar feature or plan to do so.

Please clarify.

Thank you in advance,

**Comment by martinRenou** [comment]
As answered in https://github.com/jupyter-xeus/xeus-python/issues/591, xeus-python exposes JavaScript APIs through https://github.com/emscripten-forge/pyjs
