### ISSUE TITLE
Publish 1.0.0?

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#197]
Currently the latest `1.0.0` pre-release is `1.0.0b0`: https://github.com/jupyterlite/xeus-python-kernel/releases/tag/v1.0.0b0

Should there be a new `rc`, or maybe final `1.0.0` directly?

cc @martinRenou who handled the `1.0.0b0`.

**Comment by martinRenou** [comment]
Yeah will do the final

**Comment by jtpio** [comment]
Closing as `1.0.0` is now available: https://github.com/jupyterlite/xeus-python-kernel/releases/tag/v1.0.0

Thanks @martinRenou!
