### ISSUE TITLE
Compatibility with "ignore_sys_prefix"

### ISSUE THREAD

**Issue by benbovy** [jupyterlite/xeus-python-kernel#22]
## Description

I'm trying to use this jupyterlite addon in a custom jupyterlite deployment built via jupyterlite-sphinx. However, I'm struggling to get it working and I'm wondering if it's not related to the way this addon behaves with the `ignore-sys-prefix` JupyterLite setting. None of the values set below for this setting yields the expected results (I guess?).

## Reproduce

My custom jupyter lite build is very similar to the example given in this documentation and the one used for the ipycanvas documentation. I use the following packages:

```
  "XeusPythonEnv": {
    "packages": ["numpy", "matplotlib", "ipytone", "jupyterlab_widgets", "traitlets", "traittypes", "ipywidgets"]
  },

```

### 1. Using `ignore-sys-prefix: true`

- No `xeus-python` kernel visible in the list of kernels and no federated extension copied into the JupyterLite build

- Content of `build/html/lite/jupyter-lite.json`:

```json
{
  "jupyter-config-data": {
    "appName": "JupyterLite",
    "appUrl": "./lab",
    "appVersion": "0.1.0-beta.7",
    "baseUrl": "./",
    "faviconUrl": "./lab/favicon.ico",
    "federated_extensions": [],
    "fullLabextensionsUrl": "./extensions",
    "fullMathjaxUrl": "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js",
    "fullStaticUrl": "./build",
    "licensesUrl": "./lab/api/licenses",
    "mathjaxConfig": "TeX-AMS_CHTML-full,Safe",
    "preferredPath": "/"
  },
  "jupyter-lite-schema-version": 0
}%
```

- Content of `build/html/lite/extensions` directory:

```
@jupyterlite/xeus-python-kernel
```

### 2. Using `ignore-sys-prefix: []`

- `xeus-python` kernel visible in the list of kernels and all federated extensions installed in my environment copied into the JupyterLite build (which is not what I expect and which may have different versions than the versions installed in the xeus environment)

- Content of `build/html/lite/jupyter-lite.json`:

```json
{
  "jupyter-config-data": {
    "appName": "JupyterLite",
    "appUrl": "./lab",
    "appVersion": "0.1.0-beta.7",
    "baseUrl": "./",
    "faviconUrl": "./lab/favicon.ico",
    "federated_extensions": [
        {
            "extension": "./extension",
            "liteExtension": true,
            "load": "static/remoteEntry.7363ca86b6eb68446da2.js",
            "name": "@jupyterlite/xeus-python-kernel",
            "style": "./style"
        },
        ... all extensions from my jupyterlab env ...
    ],
    "fullLabextensionsUrl": "./extensions",
    "fullMathjaxUrl": "./static/jupyter_server_mathjax/MathJax.js",
    "fullStaticUrl": "./build",
    "licensesUrl": "./lab/api/licenses",
    "mathjaxConfig": "TeX-AMS-MML_HTMLorMML-full,Safe",
    "preferredPath": "/"
  },
  "jupyter-lite-schema-version": 0
}%
```

- Content of `build/html/lite/extensions` directory:

```
@jupyterlite/xeus-python-kernel
+ all extensions from my jupyterlab env
```

### 3. Using `ignore-sys-prefix: ["jupyterlite-xeus-python"]`

Same results than with 2.

### 4. Using `ignore-sys-prefix: ["federated_extensions"]`

- No `xeus-python` kernel visible in the list of kernels and but the expected federated extensions are copied into the JupyterLite build

- Content of `build/html/lite/jupyter-lite.json`:

```json
{
  "jupyter-config-data": {
    "appName": "JupyterLite",
    "appUrl": "./lab",
    "appVersion": "0.1.0-beta.7",
    "baseUrl": "./",
    "faviconUrl": "./lab/favicon.ico",
    "federated_extensions": [
      {
        "extension": "./extension",
        "liteExtension": false,
        "load": "static/remoteEntry.3421943a0ce73f10909d.js",
        "name": "@jupyter-widgets/jupyterlab-manager"
      },
      {
        "extension": "./extension",
        "liteExtension": false,
        "load": "static/remoteEntry.31dd2990580e09632145.js",
        "name": "ipytone"
      }
    ],
    "fullLabextensionsUrl": "./extensions",
    "fullMathjaxUrl": "./static/jupyter_server_mathjax/MathJax.js",
    "fullStaticUrl": "./build",
    "licensesUrl": "./lab/api/licenses",
    "mathjaxConfig": "TeX-AMS-MML_HTMLorMML-full,Safe",
    "preferredPath": "/"
  },
  "jupyter-lite-schema-version": 0
}%
```

- Content of `build/html/lite/extensions` directory:

```
@jupyterlite/xeus-python-kernel   # although not all files are present (remoteEntry, etc.)
@jupyter-widgets
ipytone
```

## Expected behavior

- `xeus-python` kernel visible in the list of kernels.
- Only the (non-jupyterlite) federated extensions installed from `XeusPythonEnv` packages copied into the JupyterLite build

## Context

- JupyterLite version: 0.1.0b7
- Jupyterlite-sphinx: 0.4.7 (with patch so that the build completes #21)
- jupyterlite-xeus-python: 0.3.0

**Comment by martinRenou** [comment]
Thank you for the detailed issue. Indeed I've seen similar issues when making the ipycanvas deployment recently.

It also conflicts a lot with the core FederatedExtensions addon that JupyterLite provides.

A PR would be super appreciated :) Otherwise I will find some time to tackle this properly.

**Comment by benbovy** [comment]
Thanks, and no rush!

I could try to find some time too, but I would first need to get more familiar with JupyterLite and the whole toolchain that it uses.

**Comment by jtpio** [comment]
Linking to https://github.com/jupyterlite/jupyterlite/pull/621 for reference where `ignore_sys_prefix` was made easier to configure for addons.

> It also conflicts a lot with the core FederatedExtensions addon that JupyterLite provides.

Wondering if this is indeed because the xeus python addon reuses `is_sys_prefix_ignored` from the `federated_extensions` addon:

https://github.com/jupyterlite/xeus-python-kernel/blob/dd8e043b867867e96f9081a1003115e1cd9ba8fd/jupyterlite_xeus_python/env_build_addon.py#L110

**Comment by benbovy** [comment]
If my understanding is correct, this add-on should:

1. always copy the `@jupyterlite/xeus-python-kernel` federated extension from the active environment
2. overwrite the python_data.{js,data} generated by this add-on into the extension copied above
3. copy the federated extensions that have been installed in the `/tmp/xeus/tmp/xeus-python-kernel/envs/xeus-python-kernel` environment by this add-on.

This add-on should never copy other federated extensions from the active environment than (1), as they could potentially conflict with the federated extensions that have been installed in  `/tmp/xeus/tmp/xeus-python-kernel/envs/xeus-python-kernel`. So `ignore_sys_prefix` is actually not useful for this add-on and could be ignored?

Perhaps another solution might be to install jupyterlite and jupyterlite-xeus-python in `/tmp/xeus/tmp/xeus-python-kernel/envs/xeus-python-kernel` (and ensure that the same versions are installed than in the active environment)?
