### ISSUE TITLE
Add UI-tests

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/xeus-python-kernel#29]
### Problem

We need to add some tests for the kernel:
- Make sure it shows up in the JupyterLite UI
- Make sure it can execute code and have access to the file system

**Comment by jtpio** [comment]
This would indeed be useful :+1: 

For example we could test on `chromium`, `firefox` and `webkit` to potentially catch issues as reported in https://github.com/jupyterlite/jupyterlite/issues/944 (and investigated in https://github.com/jupyterlite/jupyterlite/pull/1190).

**Comment by jtpio** [comment]
Starting this in https://github.com/jupyterlite/xeus-python-kernel/pull/167
