### ISSUE TITLE
ModuleNotFoundError: No module named 'webbrowser'

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#50]
## Description

Adding `plotly` to `XeusPythonEnv.packages` and importing it in a notebook results in the following:

```
ModuleNotFoundError: No module named 'webbrowser'
```

## Reproduce

For example this deployment: https://scipy-2022-jupyterlite-virtual-poster--7.org.readthedocs.build/en/7/lite/lab/index.html?path=plotly.ipynb

Although the link will probably be invalid soon.

## Expected behavior

Running `import webbrowser` on the Pyodide console works fine: https://pyodide.org/en/latest/console.html

![image](https://user-images.githubusercontent.com/591645/176381160-d05aa814-a6f7-467e-bc6e-f6dcda0ebc6a.png)

## Context

`plotly` depends on the `webbrowser` module being available.

**Comment by DerThorsten** [comment]
Thanks for reporting this,
I had a look how pyodide is doing this: 
Actualy they add their own implementation of `webbrowser` [here](https://github.com/pyodide/pyodide/blob/main/src/py/lib/webbrowser.py): 

They do:
```python
#! /usr/bin/env python3

"""
An implementation of the standard library webbrowser module to open webpages.
Since we're already running a webbrowser, it's really simple...
"""


def open(url, new=0, autoraise=True):
    from js import window

    window.open(url, "_blank")


def open_new(url):
    return open(url, 1)


def open_new_tab(url):
    return open(url, 2)
```

So this wont work since we are running in a worker and do not have access to the js `window` from the worker, right?

**Comment by martinRenou** [comment]
Maybe the service worker could help here

**Comment by martinRenou** [comment]
In the meantime we could provide a `webbrowser` mock that is a no-op, just to get the import to not fail at least, and having plotly support.

**Comment by jtpio** [comment]
> So this wont work since we are running in a worker and do not have access to the js `window` from the worker, right?

Right, but in the case of `plotly` what is only required is being able to import the module with `import webbrowser`.

**Comment by jtpio** [comment]
They import it here: https://github.com/plotly/plotly.py/blob/1f19f5f76a7bebe6241fc7402233f22931dbe89a/packages/python/plotly/plotly/io/_base_renderers.py#L4

Although they could also delay the import at a later point: https://github.com/plotly/plotly.py/blob/1f19f5f76a7bebe6241fc7402233f22931dbe89a/packages/python/plotly/plotly/io/_base_renderers.py#L673

**Comment by martinRenou** [comment]
I will push a PR to xeus-python-shell adding a mock for `webbrowser`

**Comment by martinRenou** [comment]
xeus-python-shell 0.4.2 with a `webbrowser` mock is out. If you try rebuilding your docs it should work.

**Comment by martinRenou** [comment]
> we could also do:

Yes and no. It would work indeed, but it would also reopen the url if you save the Notebook and open it again, which is a side effect we probably don't want.

**Comment by martinRenou** [comment]
If you save the Notebook, it will save the `window.open("{url}");` JavaScript tag in the output cell. Then if you re-open the Notebook, this JavaScript tag should be added again and executed again.

**Comment by DerThorsten** [comment]
I see, thanks for the clarification

**Comment by jtpio** [comment]
Closing as fixed, thanks all!

![image](https://user-images.githubusercontent.com/591645/176625382-449b73be-d264-4643-a702-30f0f61d8045.png)
