### ISSUE TITLE
`UserWarning: I/O error(44): No such file or directory` when importing `pandas`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#55]
Currently importing `pandas` gives the following warning:

```
/tmp/xeus-python-kernel/envs/xeus-python-kernel/lib/python3.10/site-packages/dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(44): No such file or directory
  warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
```

This does not seem to be the case with Pyodide:

![image](https://user-images.githubusercontent.com/591645/178224318-32d2c4f6-f9b5-4f2f-b9fc-16510b5b2a49.png)

In this example the version is not exactly the same which might explain the difference (although unlikely?).

**Comment by DerThorsten** [comment]
I think we are filtering out `ZONEFILENAME = "dateutil-zoneinfo.tar.gz"` (
https://github.com/dateutil/dateutil/blob/7c5c98959bd0e9eea3c55fdf78bef3ae5b8c995e/src/dateutil/zoneinfo/__init__.py#L13) when we pack the package for the emscripten-virtual filesystem.

**Comment by martinRenou** [comment]
Maybe we should not filter out anything from the site-packages directory? That way we don't filter package data. Will it impact the resulting wheel size a lot?

**Comment by DerThorsten** [comment]
unfortunately, that will impact the size a lot. 
But I am working on the following: There will be a default filter / include/ignore pattern.  But recipes can overwrite  this behavior.

**Comment by martinRenou** [comment]
> But recipes can overwrite this behavior

Great!

**Comment by martinRenou** [comment]
Should be fixed now
