### ISSUE TITLE
Does not load in Firefox

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-python-kernel#6]
First of all, really impressive work to get xeus-python to compile to WebAssembly!

## Description

Looks like the kernel does not load in Firefox though. The error logged in the dev tools might be relevant:

```
TypeError: WebAssembly.Tag is not a constructor
``` 

![image](https://user-images.githubusercontent.com/591645/168019279-fb3862d4-54bd-48cd-8436-3de5f9791d5e.png)

## Reproduce

Open https://xeus-python-kernel.readthedocs.io/en/latest/ with Firefox 99.

## Expected behavior

Should run in Firefox.

**Comment by jtpio** [comment]
Interestingly, it loads fine in Firefox 101.0b5 (Firefox Developer Edition).

![image](https://user-images.githubusercontent.com/591645/168020288-eb53e9b0-975b-4eb1-9c57-f224bfff282f.png)

So maybe not much to be done here for now if future versions of Firefox are not impacted.

**Comment by martinRenou** [comment]
Maybe upgrading to 100 should be enough? I see it working on 100:

![xeus-firefox](https://user-images.githubusercontent.com/21197331/168020532-12a8ebec-3bb8-4443-a20e-94196cd9d185.png)

**Comment by jtpio** [comment]
> Maybe upgrading to 100 should be enough? I see it working on 100:

Yes similar observation in https://github.com/jupyterlite/xeus-python-kernel/issues/6#issuecomment-1124652376.

Let's close this since it's fine the latest stable version. Thanks for checking!
