### ISSUE TITLE
`import pandas` hangs with jupyterlite-xeus-python 0.5.4 and jupyterlite 0.1.0b12

### ISSUE THREAD

**Issue by vasiljevic** [jupyterlite/xeus-python-kernel#67]
## Description

Execusion of cell `import pandas` hangs. This exception message is shown on the JavaScript Console:

Uncaught (in promise) SyntaxError: Unexpected end of input (at services.js:32:51)
    at services.js:32:51
    at new Promise (<anonymous>)
    at services.js:28:7

## Reproduce

1. have installed jupyterlite 0.1.0b12 and jupyterlite-xeus-python 0.5.4
2. init new site and build it width `jupyter lite build --XeusPythonEnv.packages=openpyxl,pandas,matplotlib`
3. Open site in the browser
4. Create new notebook and select Xeus-python kernel
5. Add cell with `import pandas` and run it
6. Go to JavaScript console and see an exeption like this: Uncaught (in promise) SyntaxError: Unexpected end of input (at services.js:32:51) ...

## Expected behavior

Pandas should be normally imported in several seconds

## Context

- JupyterLite version: 0.1.0b12
- Xeus Pzthon Kernel version: 0.5.4
- Operating System and version: Ubuntu 22.04 (WSL)
- Browser and version: Chrome version 104.0.5112.81 (Official Build) (64-bit) on Windows 10

<details><summary>Browser Output</summary>
<pre>
Uncaught (in promise) SyntaxError: Unexpected end of input (at services.js:32:51)
    at services.js:32:51
    at new Promise (<anonymous>)
    at services.js:28:7
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @vasiljevic for reporting.

`0.1.0b12` was just released which includes some changes that might be related such as https://github.com/jupyterlite/jupyterlite/pull/753.

Importing `pandas` seems to be working fine with the Pyodide kernel. So it might be that jupyterlite-xeus-python needs to adapt to these upstream changes.

![image](https://user-images.githubusercontent.com/591645/185107215-3cdd15ce-490f-46ff-bc88-05f225afa45e.png)

**Comment by martinRenou** [comment]
Thanks! I'll have a look

**Comment by vasiljevic** [comment]
> Importing `pandas` seems to be working fine with the Pyodide kernel.

I know, but in Pyodide kernel I can't easily build environment with preinstalled packages like openpyxl (without the need to put piplite.install/micropip.install in my notebook)

**Comment by jtpio** [comment]
> I know, but in Pyodide kernel I can't easily build environment with preinstalled packages like openpyxl (without the need to put piplite.install/micropip.install in my notebook)

Sure, it was just to double check whether this was an issue in JupyterLite or in jupyterlite-xeus-kernel.

**Comment by martinRenou** [comment]
I was wondering if it could also be due to latest `empack` release, but that doesn't seem to be the case.

It's really when updating to jupyterlite 0.1.0b12 that it breaks. I'm investigating.

**Comment by martinRenou** [comment]
I guess this code needs updating https://github.com/jupyterlite/xeus-python-kernel/blob/main/src/worker.ts#L21 now with the latest jupyterlite.

This piece of code is a weird corner case that xeus-python is having with the DriveFS that I don't understand. It should probably not be in xeus-python-kernel though, I should probably make a PR to jupyterlite.

**Comment by martinRenou** [comment]
`import pandas` seems to work again with jupyterlite-xeus-python 0.5.5. Thanks a lot for reporting!!

**Comment by vasiljevic** [comment]
> `import pandas` seems to work again with jupyterlite-xeus-python 0.5.5. Thanks a lot for reporting!!

Works in my project too :)  Thank **You**!
