### ISSUE TITLE
Default backend resolution for Matplotlib should be `inline`

### ISSUE THREAD

**Issue by vasiljevic** [jupyterlite/xeus-python-kernel#71]
###  With default backend `agg`, JypyterLite/XPython has trouble to show graphics inline
![image](https://user-images.githubusercontent.com/10418572/185780839-78efb3ae-31b1-4d35-adba-93dfb479e355.png)

The workaround is to add `%matplotlib inline`, but this should not be necessary. BTW, this command just sets the Matplotlib backend.

### This is how newer JupyterLab/IPython runs the same example
![image](https://user-images.githubusercontent.com/10418572/185781062-3d39e28d-2d00-45ba-8dde-dba9c2b2dac4.png)

### And tihis is how JupyterLite/Pyodide runs the same example
![image](https://user-images.githubusercontent.com/10418572/185780904-7f05c218-7005-4460-9b36-f7295e2c9f8d.png)

There is a trick (explained below) how Pyodide kernel does it.

## Reproduce

As explained in the description

## Expected behavior

Expected behavior is like  JupyterLab/IPython  behaves (in the above description)

Pyodide kernel paches the [matplotlib.pyplot.show](https://github.com/jupyterlite/jupyterlite/blob/c9846beca88cd84e15119547b00240515c7e6f6d/packages/pyolite-kernel/py/pyolite/pyolite/patches.py#L24)  function in runtime to enable similar behavior 

XPython kernel already behave properly when the Matplnotlib backend is `inline` since `%matplotlib inline` sets this backend. We only need to make the `inline` backend setted initialy.

Matplotlib [uses the `MPLBACKEND` environment variable in the backend resolution 
](https://github.com/matplotlib/matplotlib/blob/87595b9916919c8b951e29f2105c9cfce93e6293/lib/matplotlib/__init__.py#L1169)

So, it should be enouth to add

`os.environ["MPLBACKEND"] = 'module://matplotlib_inline.backend_inline'`

somewhere early enough in the XPython kernel. I have tried to figure out where it could be, but I am not familiar how XPython kernel works. I have tested inside a notebook:

![image](https://user-images.githubusercontent.com/10418572/185782556-ba48ae2e-7364-4b54-b232-a2e0645cecc3.png)

## Context

`plt.show()`  should work without `
- JupyterLite version: latest
- Operating System and version: Windows 10
- Browser and version: Chrome, latest

**Comment by vasiljevic** [comment]
I have found where ipykernel sets default  inline backend:
[`os.environ["MPLBACKEND"] = "module://matplotlib_inline.backend_inline"`](https://github.com/ipython/ipykernel/blob/d02f4371348187c3e5e87a46388bbef92615c110/ipykernel/kernelapp.py#L557)


This is in the definition of class:
[class IPKernelApp(BaseIPythonApplication, InteractiveShellApp, ConnectionFileMixin)](https://github.com/ipython/ipykernel/blob/d02f4371348187c3e5e87a46388bbef92615c110/ipykernel/kernelapp.py#L113)

Consequently, we may make an apppropriate modification inside:
[class XPythonShellApp(BaseIPythonApplication, InteractiveShellApp)](https://github.com/jupyter-xeus/xeus-python-shell/blob/b4bcbd7ae70a3dc5fd4d2540495aeef04e8d7638/xeus_python_shell/shell.py#L82)

in  [def initialize(self, argv=None)](https://github.com/jupyter-xeus/xeus-python-shell/blob/b4bcbd7ae70a3dc5fd4d2540495aeef04e8d7638/xeus_python_shell/shell.py#L83) after [self.init_shell()](https://github.com/jupyter-xeus/xeus-python-shell/blob/b4bcbd7ae70a3dc5fd4d2540495aeef04e8d7638/xeus_python_shell/shell.py#L91) we could just add those lines:

```
if self.shell:
    if not os.environ.get("MPLBACKEND"):
        os.environ["MPLBACKEND"] = "module://matplotlib_inline.backend_inline"
    self.init_gui_pylab()
```

**Comment by martinRenou** [comment]
Thanks a lot for reporting! And thank you for the deep investigation, would you like to push a PR against xeus-python-shell proposing your patch?
