### ISSUE TITLE
Path('.').is_dir() returns False in XPython kernel

### ISSUE THREAD

**Issue by vasiljevic** [jupyterlite/xeus-python-kernel#85]
## Description

`pathlib.Path('.').is_dir()` incorrectly returns False when run in XPython kernel.

Since Pandas use `is_dir()` in [file path checking](https://github.com/pandas-dev/pandas/blob/c04bba47d09f56101932d673db53a7ae37086132/pandas/io/common.py#L585), some Pandas I/O methods like  `DataFrame.to_csv()` fails in XPython with the error *Cannot save file into a non-existent directory: '.'*

## Reproduce

1. Create new notebook using XPython kernel
2. Run this code in a cell:
```python
from pathlib import Path
Path('.').is_dir()
```
3. See incorrect result `False`

## Expected behavior

The result of above cell should be `True` as it is in the Pyodide kernel.

## Context

- JupyterLite version: 0.1.0-beta.15
- jupyterlite-xeus-python version: 0.5.6
- Operating System and version: Ubuntu 22.04 LTS (WSL)
- Browser and version: Chrome Version 108.0.5359.71 (Official Build) (64-bit)

**Comment by vasiljevic** [comment]
It seams the issue does not exist in https://jupyterlite.github.io/xeus-python-demo/retro/notebooks/?path=demo.ipynb (jupyterlite-xeus-python 0.6.1 and JupyterLite  0.1.0-beta.16). I will dig a little bit more.

**Comment by martinRenou** [comment]
Thanks for trying! There have been some changes in the custom JupyterLite File System that may have fixed it.
